
SELECT GETDATE()

-- CAST Function

SELECT CAST(GETDATE() AS DATE)

SELECT CAST('1234.4567' AS decimal(18,3))
SELECT CAST('1234' AS INT)

-- CONVERT Function

SELECT CONVERT(NVARCHAR(20), CAST(GETDATE() AS DATE), 112)
SELECT CONVERT(NVARCHAR(20), CAST(GETDATE() AS DATE), 106)
SELECT CONVERT(NVARCHAR(20), CAST(GETDATE() AS DATE), 103)

SELECT CONVERT(NVARCHAR(20), GETDATE(), 1)
SELECT CONVERT(NVARCHAR(20), GETDATE(), 2)
SELECT CONVERT(NVARCHAR(20), GETDATE(), 8)
SELECT CONVERT(NVARCHAR(20), GETDATE(), 12)

-- FORMAT Function

SELECT FORMAT(GETDATE(),'dd-MMM-yyyy')
SELECT FORMAT(GETDATE(),'dd-MMMM-yyyy')
SELECT FORMAT(GETDATE(),'dd-MM-yyyy')
SELECT FORMAT(GETDATE(),'yyyy-MM-dd')
SELECT FORMAT(GETDATE(),'yyyy-MM-dd hh:mm:ss')
SELECT FORMAT(GETDATE(),'yyyy-MM-dd hh:mm:ss tt')

SELECT FORMAT(4, '0000')
SELECT FORMAT(124, '0000')

-- DATEADD Function

SELECT DATEADD(YEAR, -1, GETDATE())
SELECT DATEADD(YEAR, 1, GETDATE())
SELECT DATEADD(DAY, 1, GETDATE())
SELECT DATEADD(MONTH, 1, GETDATE())

-- DATENAME Function

SELECT DATENAME(YEAR, GETDATE())
SELECT DATENAME(MONTH, GETDATE())
SELECT DATENAME(WEEK, GETDATE())
SELECT DATENAME(WEEKDAY, GETDATE())
SELECT DATENAME(DW, GETDATE())
SELECT EOMONTH (GETDATE())